package calculadorcita;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
/**
 * 
 * @author Yessid Murcia
 */
public class Matriz_Traza extends javax.swing.JFrame {

    private CalculadoraDeMatrices matrizA;   
    private int dimensionx;
    private int dimensiony;
    
    public Matriz_Traza() {
        initComponents();
    }

    public Matriz_Traza(int dimensionx,int dimensiony) {
        initComponents();
        setTitle("Traza de matrices");
        setDimensionx(dimensionx);
        setDimensiony(dimensiony);
        setMatrizA(new CalculadoraDeMatrices(this.dimensionx, this.dimensiony));
        createMatrizA(MatrizA, this.matrizA);
        pack();
        
    }
    
    /**
     * Crea matriz en la interfaz
     */
    private void createMatrizA(JPanel container, CalculadoraDeMatrices matriz) {
        //bordes y layout de contenedor
        container.setBorder(BorderFactory.createMatteBorder(0, 2, 0, 2, new Color(0, 0, 0)));
        container.setLayout(new java.awt.GridLayout(this.dimensionx, this.dimensiony));

        JCTextField[][] m = matriz.getMatriz();
        for (int fila = 0; fila < this.dimensionx; fila++) {
            for (int columna = 0; columna < this.dimensiony; columna++) {
                container.add(m[fila][columna]);
            }
        }
        container.setSize(4 + this.dimensionx * 36, this.dimensiony * 36);
        container.setPreferredSize(new Dimension(4 + this.dimensionx * 36, this.dimensiony * 36));
        container.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        MatrizA = new javax.swing.JPanel();
        btnRseolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        MatrizA.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 0, 2, new java.awt.Color(0, 0, 0)));
        MatrizA.setMinimumSize(new java.awt.Dimension(100, 100));
        MatrizA.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout MatrizALayout = new javax.swing.GroupLayout(MatrizA);
        MatrizA.setLayout(MatrizALayout);
        MatrizALayout.setHorizontalGroup(
            MatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        MatrizALayout.setVerticalGroup(
            MatrizALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(MatrizA, gridBagConstraints);

        btnRseolver.setText("Resolver");
        btnRseolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRseolverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(btnRseolver, gridBagConstraints);

        getContentPane().add(jPanel3, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRseolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRseolverActionPerformed
        matrizA.traza(matrizA.getMatriz());        
    }//GEN-LAST:event_btnRseolverActionPerformed
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matriz_Traza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matriz_Traza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matriz_Traza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matriz_Traza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matriz_Traza().setVisible(true);
            }
        });
    }
     public int getDimensionx() {
        return dimensionx;
    }

    public int getDimensiony() {
        return dimensiony;
    }

    public void setDimensionx(int dimensionx) {
        this.dimensionx = dimensionx;
    }

    public void setDimensiony(int dimensiony) {
        this.dimensiony = dimensiony;
    }

    public CalculadoraDeMatrices getMatrizA() {
        return matrizA;
    }

    public void setMatrizA(CalculadoraDeMatrices matrizA) {
        this.matrizA = matrizA;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MatrizA;
    private javax.swing.JButton btnRseolver;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
